development:
  adapter: postgresql
  encoding: unicode
  database: movie_db_development
  pool: 5
  username: benjamin
  password: xiangqu53
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: movie_db_test
  pool: 5
  username: benjamin
  password: xiangqu53
  timeout: 5000