# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a9de4ff3505ae3ab23f81acfab72d68158c148282f2ea5686cd4175fa63e271acbea61925b7f6b71796ea9adc44291b1fa69aeb50a8c8cd90651619b7ab49c6

test:
  secret_key_base: cfbdf28244c16289c244938517f25462ea521e7a12e06cf76fef1bd1718fc502c05af042ff730ec9ea38242f6186750d1768be5ca3ea1603da15bc39b17a7528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
